echo "Running OOD experiments"
echo "________________________________________________________"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/iac
echo "Finished iac"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/fnc-1-ours
echo "Finished fnc-1-ours"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/politicaldebates
echo "Finished politicaldebates"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/arc
echo "Finished arc"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/emergent
echo "Finished emergent"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/perspectrum
echo "Finished perspectrum"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/snopes
echo "Finished snopes"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/wtwt
echo "Finished wtwt"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/semeval2016task6
echo "Finished semeval2016task6"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/mtsd
echo "Finished mtsd"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/vast
echo "Finished vast"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/scd
echo "Finished scd"
python weaklabeler/fewShot/train.py --experiment_name fewShot_epochs=5_n=8000_contrastive=True_ood=True --feat_extractor roberta-large --training_path weaklabeler/Data/stance_data/stance_data.csv --model_save_path weaklabeler/models/ --valid_path weaklabeler/Data/stance_data/stance_test_data_sample.csv --num_labels 4 --batch_size 4 --epochs 5 --learning_rate 0.00001 --shot_num 8000 --val_step 1 --text_col text --target_col label_name --target_config_path weaklabeler/configs/few_shot_diverse_sample.json --contrastive --filter_out dataset_name/rumor
echo "Finished rumor"
echo "________________________________________________________"
echo "Finished all datasets"